CREATE TABLE monitored_targets (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE scans (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    target_id INTEGER NOT NULL REFERENCES monitored_targets(id),
    status_code INTEGER NOT NULL,
    response_time_ms INTEGER NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    scanned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
